Fix syntax

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -16,15 +16,15 @@ runs:
       run: pip install artefacts-client --extra-index-url https://d5cw4z7oemmfd.cloudfront.net/pep503/
       shell: bash
 
-  - name: Run remote job
-    id: run-job
-    run: |
-      ARTEFACTS_KEY=${{ inputs.artefacts_api_key }} artefacts run-remote command ${{ inputs.job_name }}
-      if [ ${{ steps.run-job.exitcode }} -eq 0 ]; then
-        echo "Simulation job succeeded"
-      else
-        echo "Simulation job failed"
-        exit 1
-      fi
+    - name: Run remote job
+      id: run-job
+      run: |
+        ARTEFACTS_KEY=${{ inputs.artefacts_api_key }} artefacts run-remote command ${{ inputs.job_name }}
+        if [ ${{ steps.run-job.exitcode }} -eq 0 ]; then
+          echo "Simulation job succeeded"
+        else
+          echo "Simulation job failed"
+          exit 1
+        fi
 
-    shell: bash
+      shell: bash
