Create composite action

diff --git a/.github/workflows/trigger-job.yaml b/.github/workflows/trigger-job.yaml
--- a/.github/workflows/trigger-job.yaml
+++ b/.github/workflows/trigger-job.yaml
@@ -1,30 +1,40 @@
-name: Trigger Artefacts job
-on:
-  push:
-    branches:
-      - main
+name: 'runsimjob'
+description: 'Run Simulation Job using Artefacts'
 
-jobs:
-  trigger-job:
-    runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        python-version: [3.9]  
-    env:
-        GH_TOKEN: ${{ github.token }}
-    steps:
-    - name: Checkout repository
-      uses: actions/checkout@v3
+inputs:
+  artefacts_api_key:
+    description: 'Artefacts API Key'
+    required: true
+    default: ${{ secrets.ARTEFACTS_API_KEY }}
+  job_name:
+    description: 'Name of the job to execute'
+    required: true
 
-    - name: Set Up Python ${{ matrix.python-version }}
-      uses: actions/setup-python@v4
-      with:
-        python-version: ${{ matrix.python-version }}
-        
-    - name: Install Artefacts Client
+runs:
+  using: "composite"
+  steps:
+    - name: Install artefacts client
+      run: pip install artefacts-client --extra-index-url https://d5cw4z7oemmfd.cloudfront.net/pep503/
+
+    - name: Run remote job
+      id: run-job
       run: |
-        gh repo clone art-e-fact/artefacts-client
-        cd artefacts-client
-        pip install --editable .
+        artefacts run-remote command --api-key ${{ inputs.artefacts_api_key }} --job-name ${{ inputs.job_name }}
 
+    - name: Set action result based on exit code
+      id: set-action-result
+      run: |
+        if [ ${{ steps.run-job.exitcode }} -eq 0 ]; then
+          echo "::set-output name=action-result::success"
+        else
+          echo "::set-output name=action-result::failure"
 
+    - name: Check run remote status
+      run: |
+        if [ "${{ steps.set-action-result.outputs.action-result }}" == "success" ]; then
+          exit 0
+        else
+          exit 1
+
+      # This is important to set the exit status of the action
+      shell: bash
